---
title: "Publications et présentations"
author: ''
date: '2019-12-09'
slug: publi
categories: []
tags: []
type: "page"
---
## Notes d'analyses

#### Sur les compétences

+ "Quelles compétences pour quels territoires ?", *Éclairages et Synthèses*, à paraître	en 2020	(co-écrit avec Frédéric Lainé)

#### Sur les offres d'emploi et les besoins en main d'œuvre

+ "Les offres déposées à Pôle emploi depuis 20 ans. Reflet des évolutions du marché du travail",	*Éclairages et Synthèses*, à paraître	en 2020	

+ "Enquête "Besoins en main-d'œuvre", les employeurs anticipent une forte progression de leurs perspectives d'embauche pour 2019", *Éclairages et Synthèses*, n°52, 2019	(co-écrit avec Patrick Duchen, Sandré Gaumont et Frédéric Lainé) - https://statistiques.pole-emploi.org/bmo/Handlers/HTFile.ashx?FZD=b%2f4k%2fqAkpLhpTtCAvMpR3w%3d%3d&SITEKEY=620c8132-d522-44fa-8efa-27a62c26702c

#### Sur les assistantes maternelles

+ "Les assistant·e·s maternel·le·s ont gagné en moyenne 1 108 euros en juin 2014", *Études et Résultats*, n°1020, 2017 (co-écrit avec Nicolas Paliod) - https://drees.solidarites-sante.gouv.fr/IMG/pdf/er1020.pdf

+ "Les assistantes maternelles gardent 8 % d’enfants de plus en 2014 qu’en 2010", *Études et Résultats*, n°978, 2016 - https://drees.solidarites-sante.gouv.fr/IMG/pdf/er978.pdf

#### Sur l'emploi et la formation dans l'action sociale et médico-sociale

+ "115 000 personnes travaillent en 2016 dans le secteur de l’action sociale et médico-sociale des départements", *Études et Résultats*, n°1054, 2018 (co-écrit avec Élise Amar) - https://drees.solidarites-sante.gouv.fr/IMG/pdf/er1054.pdf

+ "Des conditions de travail en EHPAD vécues comme difficiles par des personnels très engagés", *Les Dossiers de la Drees*, n°5, 2016 (co-écrit avec Rémy Marquier à partir d'un rapport d'ENEIS Conseil) - https://drees.solidarites-sante.gouv.fr/IMG/pdf/dd05.pdf

+ "Une baisse de 7 % des étudiants inscrits en formations sociales entre 2010 et 2015", *Études et Résultats*, n°986, 2016 - https://drees.solidarites-sante.gouv.fr/IMG/pdf/er986.pdf

+ "Formations en travail social : 62 000 étudiants en 2014", *Études et Résultats*, n°953,	2016  - https://drees.solidarites-sante.gouv.fr/IMG/pdf/er953.pdf

## Publications récurrentes

+ "L’emploi intérimaire en janvier 2018", *Statistiques et Indicateurs*, n°18_014, 2018. Publication mensuelle réalisée d'octobre 2017 à aujourd'hui - http://www.pole-emploi.org/files/live/sites/peorg/files/documents/Statistiques-et-analyses/S%26I/si_19042_interim_2019aout.pdf

+ "Les offres d’emploi diffusées par Pôle emploi au 4e trimestre 2017", *Statistiques et Indicateurs*, n°18_006, 2018. Publication trimestrielle réalisée du 4ème trimestre 2017 à aujourd'hui - https://statistiques.pole-emploi.org/offres/Handlers/HTFile.ashx?FZD=vWxl4YzZggB5amjEGNE72g%3d%3d

## Interventions orales

#### Sur le marché du travail

+ *Les tensions sur le marché du travail. Elements méthodologiques*, séminaire SEE, 2019

+ *Mesurer les tensions sur le marché du travail. Avancement des travaux*, journées nationales SEE, 209 (avec Frédéric Lainé)

+ *Les tensions sur le marché du travail*, groupe de travail sur les tensions, 2019

+ *Les offres déposées à Pôle emploi depuis 20 ans. Présentation de l'étude*, séminaire SEE, 2019

+ *Analyser les compétences demandées par les employeurs*, groupe de travail sur les compétences, 2018

#### Sur d'autres sujets

+ *Ethnographie, numérique et statistique : les Veilleurs de la "Manif pour tous"*, Nanterre	Journées d'études "De la constitution d’un corpus aux analyses statistiques comment produire des analyses quantitatives à partir de matériaux ethnographiques ?, 2016

## Articles dans des revues à comité de lecture

+ "D’une rive à l’autre du scoutisme : des aventures buissonnières à l’apprentissage de la citoyenneté", *Participations*, 2017/3, p. 49-71, 2017 (co-écrit avec Maxime Vanhoenecker qui est l'auteur principal) - https://www.cairn.info/revue-participations-2017-3-page-49.htm

+ "Politique de la ville. Que nous révèle la qualité de vie ?", *Savoir/Agir*, 2015/3, n°33, p. 103-111, 2015 - https://www.cairn.info/revue-savoir-agir-2015-3-page-103.htm

## Notes de lecture

#### Sur *Nonfiction* - https://www.nonfiction.fr

+ "Les pouvoirs du numérique" - "La datacratie", *Pouvoirs, revue française d'études constitutionnelles et politiques*, n°164, 2018 - 	https://www.nonfiction.fr/article-9291-les-pouvoirs-du-numerique.htm

+ "Qu’est-ce que vivre au milieu des algorithmes ?" - Serge Abiteboul , Valérie Peugeot, *Terra Data - Qu'allons-nous faire des données numériques ?* - Serge Abiteboul , Gilles Dowek, *Le Temps des algorithmes*, 2017 - https://www.nonfiction.fr/article-9144-quest-ce-que-vivre-au-milieu-des-algorithmes.htm

+ "Les Big Data entre promesses et dangers" - Mokrane Bouzeghoub , Remy Mosseri (dir.), *Les Big Data à découvert* - Cathy O'Neil, *Weapons of Math Destruction : How Big Data Increases Inequality and Threatens Democracy*, 2017 - 	https://www.nonfiction.fr/article-9029-les-big-data-entre-promesses-et-dangers.htm

#### Sur *Lectures* - http://journals.openedition.org/lectures

+ Michel Bierlaire, Vincent Kaufmann, Patrick Rérat (dir.), *La mobilité en questions*, 2017 - http://journals.openedition.org/lectures/23114

+ Dimitris Ballas, Danny Dorling, Benjamin Hennig, *The social atlas of Europe*,	2016 - http://journals.openedition.org/lectures/21008

+ Éric Dagiral, Jean-Noël Jouzel, Arnaud Mias, Ashveen Peerbaye (dir.), « Mesurer pour prévenir », *Terrains & Travaux*, n°28, 2016 - http://journals.openedition.org/lectures/21606

+ Cécile Touitou (dir.), *Évaluer la bibliothèque par des mesures d’impacts*, 2016 - http://journals.openedition.org/lectures/21923

+ Maria Vasconcellos, Philippe Bongrand, *Le système éducatif*, 2014 - http://journals.openedition.org/lectures/13203

+ John Rawls, *Justice et critique*, 2014 - http://journals.openedition.org/lectures/14031

+ Olivier Galland, Bernard Roudet (dir.), « Jeunes Européens : quelles valeurs en partage ? », *Agora Débats/Jeunesses*, n°67, 2014 - http://journals.openedition.org/lectures/15602

