---
title: 'Les vendanges : quels emplois ?'
author: ''
date: '2019-12-10'
slug: vendanges
categories: []
description: "L'emploi pour les vendanges est particulier car il est à la fois très localisé géographiquement et dans le temps. De plus, les personnes qui occupent ces emplois ont elles aussi des profils spécifiques."
tags:
  - R
  - emploi
  - territoires
type: "post"
---

```{r message=FALSE, warning=FALSE, include=FALSE}

library(here)

# Copie de Github
download.file("https://raw.githubusercontent.com/tvroylandt/vendanges/master/analyse_vendanges.Rmd", 
              here("static/post/analyse_vendanges.Rmmd"))

download.file("https://raw.githubusercontent.com/tvroylandt/vendanges/master/data/dads_filtre_05_15.rds", 
              here("static/post/data/dads_filtre_05_15.rds"))


# Liens symboliques à faire ensuite de façon relative en ligne de commande
# Aller dans le bon dossier
# faire ln -rs chemin_vers_le_fichier nom_du_lien
```

```{r child_doc, child = "analyse_vendanges.Rmmd"}
```
